### PR TITLE
**Please Review** Updated XML files per team meeting

### PR DESCRIPTION
**Pull request by cvhammond**
I have updated the synergy and torque driven XML files (see last commit) to match our discussion from yesterday. A few items to note:

- we are planning to change `v_max_factor` to `maxiumum_velocity_factor` or similar, please advise
- I don't want to use the plural form of controller for the settings because it could imply a 'list' structure
- The top level `<RCNLController>` could have a different name, open to suggestions
- updated `<initial_parameters_file>` to `<initial_synergy_weight_file>` to be more correct
- `<epsilon>` should have a more english-explanative name
- I want to improve the naming of `<joint_position_multiple>`, potentially something like `<joint_position_range_factor>` or similar for all of the terms with similar naming
- I want to improve the name of `<synergy_activations_max>` to something like `<maximum_allowed_synergy_activation>` or something

Please let me know if these XML files are in the spirit of our discussion yesterday and if you have any opinions about the comments!

### CODE REVIEW

**Comment by bfregly** [comment]
1) “we are planning to change v_max_factor to maxiumum_velocity_factor or similar, please advise”

I would call v_max_factor maximum_shortening_velocity_multiplier, since it is by how much we multiply optimal fiber length to get to get maximum shortening velocity.

2) I don't want to use the plural form of controller for the settings because it could imply a 'list' structure
The top level <RCNLController> could have a different name, open to suggestions

If we want to avoid a “list” structure but still get across that we are choosing types of controllers, how about something like <RCNLControlMethods>? I like having a plural name here since you can have two control types or methods, but if having the “s” included would simply a “list” still, then <RCNLControlMethod> would probably be fine, and the user could include two methods.

Just FYI, OpenSim models have controllers, and here is how they are described:

		
		<ControllerSet name="controllerset">
			<objects />
			<groups />
		</ControllerSet>

3) updated <initial_parameters_file> to <initial_synergy_weight_file> to be more correct

I would call this quantity <initial synergy_vectors_file> since the weights are contained within the vectors, and we normally talk about synergy activations and their associated synergy vectors.

4) <epsilon> should have a more english-explanative name

I agree - I don’t know what epsilon is used for.

5) I want to improve the naming of <joint_position_multiple>, potentially something like <joint_position_range_factor> or similar for all of the terms with similar naming

I would suggest <joint_position_range_scale_factor>.

6) I want to improve the name of <synergy_activations_max> to something like <maximum_allowed_synergy_activation> or something (similar issue for <synergy_weights_max>)

I would suggest <maximum_allowable_synergy_activation> and <maximum_allowable_synergy_vector_weight>.

**Comment by cvhammond** [comment]
@bfregly for item 3 on your list, did you want the element named <initial_synergy_vectors_file>?

**Comment by bfregly** [comment]
Looks like part of my response to 3) got cut off. I should have written <initial_synergy_vector_file>.

However, is it just initial? Will the synergy vectors in this file sometimes remain unchanged? Should this item be just <synergy_vector_file>?

**Comment by cvhammond** [comment]
I'm actually mistaken about this element, we are parsing the <ncp_results_directory> to get the synergy vectors, so this element should be removed

**Pull request merged**
